configs:
  -
    name: "nginx-conf-test"
    relativePath: "/ng_conf"
    port: 18080
    confPath: "/usr/local/openresty/nginx/conf/nginx.conf"
    nginxBin: "/usr/local/openresty/nginx/sbin/nginx"
#  -
#    name: "ng-conf-test2"
#    relativePath: "/ng_conf"
#    port: 28080
#    confPath: "/GO_Project/src/go-nginx-conf-parser/test/config_test/nginx.conf"
#    nginxBin: "xxxxxxxxxxxx/nginx"
DBConfig:
  DBName: "nginx_admin"
  host: "127.0.0.1"
  port: 3306
  protocol: "tcp"
  user: "ngadmin"
  password: "ngadmin"